
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:8.0  
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql  
      - ./db-init:/docker-entrypoint-initdb.d/ 
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:




  






